vim.api.nvim_set_hl(0, "NormalFloat", { bg = '#292D3E' })
vim.api.nvim_set_hl(0, "FloatBorder", { bg = '#292D3E' })
vim.api.nvim_set_hl(0, "CursorLineNr", { fg = '#FABD2F' })
vim.api.nvim_set_hl(0, "CursorLine", { bg = '#202230' })
vim.api.nvim_set_hl(0, "Search", { bg = '#202230' })
vim.api.nvim_set_hl(0, "Folded", { bg = '#292D3E' })
vim.api.nvim_set_hl(0, "FoldColumn", { fg = '#4B5263' })
vim.api.nvim_set_hl(0, "TSDefinition", { bg = '#3E4452', bold = true })
vim.api.nvim_set_hl(0, "TSDefinitionUsage", { bg = '#3E4452' })
vim.api.nvim_set_hl(0, "IlluminatedWordText", { bold = true })
vim.api.nvim_set_hl(0, "IlluminatedWordRead", { bold = true })
vim.api.nvim_set_hl(0, "IlluminatedWordWrite", { bold = true })
vim.api.nvim_set_hl(0, "NeoTreeNormal", { bg = '#242636' })
vim.api.nvim_set_hl(0, "NeoTreeNormalNC", { bg = '#242636' })
vim.api.nvim_set_hl(0, "LazyNormal", { bg = '#242636' })
vim.api.nvim_set_hl(0, "MasonNormal", { bg = '#242636' })
vim.api.nvim_set_hl(0, 'DapBreakpoint', { ctermbg = 0, fg = '#993939', bg = '#292D3E' })
vim.api.nvim_set_hl(0, 'DapLogPoint', { ctermbg = 0, fg = '#61afef', bg = '#292D3E' })
vim.api.nvim_set_hl(0, 'DapStopped', { ctermbg = 0, fg = '#98c379', bg = '#292D3E' })
vim.api.nvim_set_hl(0, "HlSearchNear", { bg = '#202230' })
vim.api.nvim_set_hl(0, "HlSearchLens", { fg = '#4B5263' })
vim.api.nvim_set_hl(0, "HlSearchLensNear", { fg = '#6D7790' })
vim.api.nvim_set_hl(0, "FlashMatch", { undercurl = true })
vim.api.nvim_set_hl(0, "FlashLabel", { undercurl = true })
vim.api.nvim_set_hl(0, "FlashCursor", { bold = true })
