vim.g.mapleader = ' '

local function remap(op, outer_opts)
	outer_opts = vim.tbl_extend("force", { noremap = true, silent = true }, outer_opts or {})

	return function(lhs, rhs, opts)
		opts = vim.tbl_extend("force", outer_opts, opts or {})
		vim.keymap.set(op, lhs, rhs, opts)
	end
end

local nnoremap = remap("n")
local vnoremap = remap("v")
local inoremap = remap("i")
local cnoremap = remap("c")

nnoremap('<leader>uu', ':UndotreeToggle<CR>')
nnoremap('Q', '@q')
nnoremap('<C-s>', ':w!<CR>')
vnoremap('<C-s>', ':w!<CR>')
inoremap('<C-s>', '<esc>:w!<CR>')
nnoremap('Y', 'y$')
vnoremap('<leader>p', '\"_dP')
vnoremap('<leader>P', '\"_dp')
nnoremap('<C-i>', '<C-p>')
nnoremap('<Tab>', '>>')
nnoremap('<S-Tab>', '<<')
vnoremap('<Tab>', '>><esc>gv')
vnoremap('<S-Tab>', '<<<esc>gv')
nnoremap('<leader>h', ':set hlsearch! hlsearch?<CR>')
-- cnoremap('W', 'exe \'w !sudo tee >/dev/null %:p:S\'<CR>')
nnoremap('<C-j>', 'J')
vnoremap('J', ":m '>+1<CR>gv=gv")
vnoremap('K', ":m '<-2<CR>gv=gv")
nnoremap('J', ":m .+1<CR>==")
nnoremap('K', ":m .-2<CR>==")
nnoremap('<C-h>', ':BufferLineCyclePrev<CR>')
nnoremap('<C-l>', ':BufferLineCycleNext<CR>')
vnoremap('<C-h>', '"1y0:help <C-r>1<CR>')
nnoremap('H', '$')
nnoremap('L', '^')
vnoremap('H', '$')
vnoremap('L', '^')
nnoremap('<leader>ss', ":%s/<C-r><C-w>/<C-r><C-w>/gc<Left><Left><Left>", { silent = false })
vnoremap('<leader>ss', 'y:%s/<C-R>"/<C-R>"/gc<Left><Left><Left>', { silent = false })
nnoremap('<C-f>', "*<Cmd>lua require('hlslens').start()<CR>", { silent = false })
vnoremap('<C-f>', "\"1y0/<C-r>1<CR><Cmd>lua require('hlslens').start()<CR>", { silent = false })
nnoremap('<C-q>', ':bd!<CR>')
nnoremap('<leader>ee', ':Neotree toggle<CR>')
nnoremap('M', '<cmd>lua require("maximizer").toggle()<CR>')
nnoremap('gp', 'gf')
nnoremap('F', '<Plug>(clever-f-repeat-back)')

vim.keymap.set({"v", "n", "o", "x"}, "<leader>cc", function()
	local count = vim.v.count
	vim.cmd.norm((count > 0 and count or "") .. "gcc")
end)
vim.keymap.set('n',        'f', '<Plug>(leap)')
vim.keymap.set('n',        'F', '<Plug>(leap-from-window)')
vim.keymap.set({'x', 'o'}, 'f', '<Plug>(leap-forward)')
vim.keymap.set({'x', 'o'}, 'F', '<Plug>(leap-backward)')
